name: Run Daily at 3PM IST

on:
  schedule:
    - cron: '0 7 * * *'  # Scheduled run: 12:30 PM IST
  workflow_dispatch:      # 🔑 Enables manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Run your script
        run: |
          python final_stock_selection.py
